image: comp1531/automarking:latest

stages:
  - checks
  - pipeline
  - deployment

before_script:
  - npm install

tests:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - SERVER_LOG=$(mktemp)
    - npm run start >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1
    - sleep 2
    - cat $SERVER_LOG

pipeline:
  stage: pipeline
  script:
    - npm install
    - npm test
  only:
    - master
    - merge_requests

linting:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - npm run lint

deployment:
  stage: deployment
  needs: [pipeline]
  resource_group: vercel-deploy
  variables:
    VERCEL_TOKEN: "sHXq1qpiX9iimPx2AOGCiodI" # change this to your vercel token
  script:
    - npm install --global vercel@canary
    - vercel pull --yes --environment=production --token=${VERCEL_TOKEN}
    - vercel deploy --prod --token=${VERCEL_TOKEN}
  only: # change this if you want to deploy from other branches
    - master
